
#
# This LookML file was generated by AtScale on 2022-01-25T16:33:32.848402Z
#
# AtScale engine version: 2021.4.0.11186
# AtScale DesignCenter version: 2021.4.0.18787
# AtScale version: 2021.4.0.4227
# Organization: default
# Project: Workshop_JMK

connection: "jmkdemo"
label: "Workshop_JMK"


include: "/views/Workshop__JMK/Workshop__JMK.view.lkml"


explore: Workshop_JMK {
  label: "Workshop_JMK"
}

